apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8practicedeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8practiceapp
  template:
    metadata:
      labels:
        app: k8practiceapp
    spec:
      containers:
        - name: k8practiceapp
          image: 09036229746/k8practice:latest
          resources:
            limits:
              cpu: "20m"
              memory: "55M"
          ports:
            - name: k8practiceport
              containerPort: 3000
